### ISSUE TITLE
Why not fetch data from your own database for random SCP?

### ISSUE THREAD

**Issue by linonetwo** [zhufree/cqbot#1]
It's said that you have a database for your ACP-Android Project.

This may enable fetching more SCP article instead of currently limited 1-161 list:

https://github.com/zhufree/cqbot/blob/dc713d6ed4d10ab34860cfcb1f968c6f21bd100c/project/plugins/scp.py#L24

**Comment by zhufree** [comment]
I believe the offcial account of SCP wiki on bilibili post articles that is not too bad( they had checked them), but totally random article in my database can't make sure that, you may roll some articles which are not easy to understand.

**Comment by linonetwo** [comment]
That makes good sense.
